parameters:
- name: runTest
  type: boolean
  default: false
  values:
    - true
    - false

pool:
  vmImage: ubuntu-latest  # Use a specific image version

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo "Building the project..."

- stage: Test
  dependsOn: Build
  condition: eq(${{ parameters.runTest }}, true)  # Runs only if checkbox is checked
  jobs:
  - job: TestJob
    steps:
    - script: echo "Running tests..."

- stage: Deploy
  dependsOn: []  # No dependency, so it always runs
  jobs:
  - job: DeployJob
    steps:
    - script: echo "Deploying..."
